### ISSUE TITLE
Feature request: dark theme

### ISSUE THREAD

**Issue by romseguy** [hc-oss/react-multi-select-component#512]
Hello, I see you're shipping default css:
```css
.rmsc {
    --rmsc-main: #4285f4;
    --rmsc-hover: #f1f3f5;
    --rmsc-selected: #e2e6ea;
    --rmsc-border: #ccc;
    --rmsc-gray: #aaa;
    --rmsc-bg: #fff;
    --rmsc-p: 10px;
    --rmsc-radius: 4px;
    --rmsc-h: 38px;
}
```
How about adding `isDark` prop to switch to dark theme? Thank you
