### ISSUE TITLE
can we remove checkbox in dropdown, how we can remove it..??

### ISSUE THREAD

**Issue by divyansh1995** [hc-oss/react-multi-select-component#556]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshzalavadiya** [comment]
@divyansh1995 you should be easily able to do this

here's sandbox https://codesandbox.io/s/youthful-ully-wocyks?file=/src/styles.css

```css
.rmsc .item-renderer input[type="checkbox"] {
  display: none;
}
```
